name: Deploy to PyPi

on:
  push:
      branches:
        - production
        - development

jobs:
  Deploy-to-PyPi:
    runs-on: ubuntu-latest
    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#
#      - name: Installing Python
#        run: sudo apt update && sudo apt install python3
#
#      - name: Installing Dependencies
#        run: python3 -m pip install -r requirements-dev.txt
#
#      - name: Running MyPy check
#        run: mypy . --install-types --non-interactive

      - name: Packaging the SDK
        env:
          ENVIRONMENT: ${{ env.GITHUB_REF }}
        run: echo "Variable is here ${{ env.GITHUB_REF }} and other one is $ENVIRONMENT"

#      - name: Uploading to PyPi
#        env:
#          PYPI_ACCESS_TOKEN: ${{ secrets.PYPI_ACCESS_TOKEN }}
#        run: twine upload -u __token__ -p $PYPI_ACCESS_TOKEN dist/*
