name: Deploy to PyPi

on:
  workflow_dispatch:
  push:
      branches:
        - production
        - development

jobs:
  Deploy-to-PyPi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Installing Python
        run: sudo apt update && sudo apt install python3.11

      - name: Installing Dependencies
        run: python3 -m pip install -r requirements-dev.txt && python3 -m pip install -r requirements.txt

      - name: Running MyPy check
        run: mypy . --install-types --non-interactive

      - name: Running Tests
        shell: bash
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
          WISE_SANDBOX_ACCOUNT_API_KEY: ${{ secrets.WISE_SANDBOX_ACCOUNT_API_KEY }}
          APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
        run: pytest --cov sirius src/tests --cov-report xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Packaging the SDK
        run: python3 setup.py sdist

      - name: Uploading to PyPi
        env:
          PYPI_ACCESS_TOKEN: ${{ secrets.PYPI_ACCESS_TOKEN }}
        run: twine upload -u __token__ -p $PYPI_ACCESS_TOKEN dist/*
