name: 'Qodana Scan'

on:
  push:
      branches:
        - production
        - development

jobs:
  Qodana-Scan:
    uses: JetBrains/qodana-action@main
    env:
      QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}